#!/bin/bash

help() {
  echo "Edit daemon service script"
  echo ""
  echo "Usage:"
  echo "  daemon edit script [options] [app_name]"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local service=$1
  local args=${@:2}
  
  if [ -z "$service" ]; then
    local available_services=($(daemon_list))
    os::inquirer service "select" available_services "Select an service ?" true
  else
    match() {
      string::match $1 ^$service
    }

    local available_services=($(array::filter match $(daemon_list)))
    local available_count=$(array::length $available_services)
    if [ $available_count -eq 0 ]; then
      log::error "no services found"
    elif [ $available_count -eq 1 ]; then
      service=$(array::first_element $available_services)
    else
      os::inquirer service "select" available_services "Select an service ?" true
    fi
  fi

  daemon::edit_script $service $args
}

run() {
  core $@
}

run $@
