#!/bin/bash

help() {
  echo "Get a daemon service logs"
  echo ""
  echo "Usage:"
  echo "  zdaemon logs [options] [app_name]"
  echo ""
  echo "Options:"
  echo "  -f, --follow  Follow logs"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  daemon_logs $@
}

run() {
  core $@
}

run $@
