#!/bin/bash

help() {
  echo "Restart a daemon service"
  echo ""
  echo "Usage:"
  echo "  zdaemon restart [options] [app_name]"
  # echo ""
  # echo "Options:"
  # echo "  -f, --follow  Follow logs"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  daemon_restart $@
}

run() {
  core $@
}

run $@
