#!/bin/bash

daemon::enable() {
  local name=$1
  if [ "$name" = "" ]; then
    log::error "name is required"
    exit 1
  fi

  local service=$(daemon_get_service_name $1)
  if [ "$(daemon_is_service_exist $1)" = "false" ]; then
    log::error "daemon service($1) not found"
    exit 1
  fi

  if [ "$(os::is_macos)" = "true" ]; then
    local service_path=$(daemon_service::get_path $1)
    sudo launchctl enable $service_path
    return
  fi

  # systemd
  if [ "$(os::has_command systemd)" = "true" ]; then
    if [ "$(os::is_docker)" != "true" ]; then
      sudo systemctl enable $service
      return $?
    fi
  fi

  # sysv
  if [ "$(os::has_command service)" = "true" ]; then
    local service_path=$(daemon_service::get_path $name)
    sudo ln -sf $service_path /etc/init.d/$name
    return $?
  fi

  log::error "unsupported os"
  return 1
}

export -f daemon::enable
