#!/bin/bash

daemon_logs() {
  local name=$1
  if [ "$name" = "" ]; then
    log::error "name is required"
    exit 1
  fi

  local service=$(daemon_get_service_name $1)
  if [ "$(daemon_is_service_exist $1)" = "false" ]; then
    log::error "daemon service($1) not found"
    exit 1
  fi

  while [[ $# -gt 0 ]]; do
    local key=$1
    local value=$2
    case $key in
    -f | --follow)
      os::set_var is_daemon_logs_follow true
      shift
      ;;
    *)
      if [ "$(string::match $key ^-)" = "true" ]; then
        log::error "[daemon_logs] unknown parameter \"$key\""
        exit 1
      fi

      shift
      ;;
    esac
  done

  if [ "$(os::is_macos)" = "true" ]; then
    # local log_path=/tmp/$service.log
    # local error_log_path=/tmp/$service.error.log
    local log_path=$(daemon_get_service_log_path $name)

    if [ "$is_daemon_logs_follow" = "true" ]; then
      tail -f $log_path
    else
      cat $log_path
    fi
    return
  fi

  if [ "$is_daemon_logs_follow" = "true" ]; then
    sudo journalctl -u $service -f
  else
    sudo journalctl -u $service -r
  fi
}

export -f daemon_logs
