#!/bin/bash

daemon::remove() {
  local name=$1

  if [ "$name" = "" ]; then
    log::error "daemon service and command are required"
    exit 1
  fi

  local service_name=$(daemon_get_service_name $name)
  local service_path=$(daemon_service::get_path $name)
  if [ "$(daemon_is_service_exist $name)" = "false" ]; then
    log::error "daemon service(${name}) not found"
    exit 1
  fi

  # 2. remove
  sudo rm -f $service_path

  if [ "$(os::is_macos)" = "true" ]; then
    # 1. stop
    daemon::stop $name
    log::success "daemon serice ${name} removed"
    return
  fi

  # systemd
  if [ "$(os::has_command systemd)" = "true" ]; then
    if [ "$(os::is_docker)" != "true" ]; then
      sudo systemctl stop $service_name
      sudo systemctl daemon-reload
      return $?
    fi
  fi

  # sysv
  if [ "$(os::has_command service)" = "true" ]; then
    sudo service $name stop
    return $?
  fi

  log::success "daemon serice ${name} removed"
}

export -f daemon::remove
