#!/bin/bash

daemon::start() {
  local name=$1
  if [ "$name" = "" ]; then
    log::error "name is required"
    exit 1
  fi

  local service=$(daemon_get_service_name $1)
  if [ "$(daemon_is_service_exist $1)" = "false" ]; then
    log::error "daemon service($1) not found"
    exit 1
  fi

  if [ "$(os::is_macos)" = "true" ]; then
    local service_path=$(daemon_service::get_path $1)
    sudo launchctl list | grep $service >>/dev/null 2>&1
    if [ "$?" != "0" ]; then
      sudo launchctl load $service_path
    fi

    return
  fi

  # systemd
  if [ "$(os::has_command systemctl)" = "true" ]; then
    if [ "$(os::is_docker)" != "true" ]; then
      sudo systemctl start $service
      return $?
    fi
  fi

  # sysv
  if [ "$(os::has_command service)" = "true" ]; then
    sudo service $name start
    return $?
  fi

  log::error "unsupported os"
  return 1
}

export -f daemon::start
